stages:
- build
- test
- deploy
########################################################################################################################
####START####                                     PROJECT LEVEL VARIABLES                                  ####START####
########################################################################################################################
variables:
  DOCKER_DRIVER: overlay2
  DEFAULT_VERUSCOIN_BRANCH: dev
  VERUS_VERSION: 0.6.3-dev-1
  VERUSCOIN_VERSION: 0.6.3
  KOMODO_VERSION: 0.5.2
  BINARY_SOURCE: VerusCoin
  EASYDEX_GUI_BUILD: build.tar.gz
  VERUS_APPIMAGE: Verus-Desktop-Linux-v${VERUS_VERSION}.AppImage
  VERUS_LINUX_TAR: Verus-Desktop-Linux-v${VERUS_VERSION}-amd64.tar.gz
  VERUS_LINUX_ARM64_TAR: Verus-Desktop-Linux-v${VERUS_VERSION}-arm64.tar.gz
  VERUS_WINDOWS_ZIP: Verus-Desktop-Windows-v${VERUS_VERSION}.zip
  VERUS_WINDOWS_NSIS: Verus-Desktop-Windows-v${VERUS_VERSION}.exe
  VERUS_MACOS: Verus-Desktop-MacOS-v${VERUS_VERSION}.dmg
  GIT_SUBMODULE_STRATEGY: recursive
  POST_COMMENT: "Pipeline Trigger: ${CI_PIPELINE_SOURCE}\n
      Branch: ${CI_COMMIT_REF_NAME}\n
      Commit: https://github.com/VerusCoin/Verus-Desktop/commit/${CI_COMMIT_SHA}\n
      ${CI_COMMIT_MESSAGE}\n"
########################################################################################################################
####END####                                        PROJECT LEVEL VARIABLES                                   ####END####
########################################################################################################################
########################################################################################################################
########################################################################################################################
####START####                                          Build Stage                                        ####START#####
########################################################################################################################
########################################################################################################################
####START####                                            LINUX                                             ####START####
########################################################################################################################
build:linux:
  image: asherd/agama-builder
  stage: build
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_LINUX="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Linux/Verus-CLI-Linux-v${VERUSCOIN_VERSION}-amd64.tar.gz"
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/Verus-Desktop-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - mkdir -p assets/bin/linux64/verusd
    - gsutil cp $STAGING/$VERUS_CLI_LINUX .
    - tar -xzvf Verus-CLI-Linux-v${VERUSCOIN_VERSION}-amd64.tar.gz --strip=1 --directory assets/bin/linux64/verusd
    - rm Verus-CLI-Linux-v${VERUSCOIN_VERSION}-amd64.tar.gz
    - gsutil cp $STAGING/VerusCoin/Zcash/zcashd-linux-amd64.tar.gz .
    - tar -xzvf zcashd-linux-amd64.tar.gz --directory assets/bin/linux64/
    - wget https://github.com/KomodoPlatform/komodo/releases/download/${KOMODO_VERSION}/linux64_${KOMODO_VERSION}.tar.gz
    - tar -xzvf linux64_${KOMODO_VERSION}.tar.gz --strip=1 --directory assets/bin/linux64
    - rm linux64_${KOMODO_VERSION}.tar.gz
    - strip --strip-unneeded  assets/bin/linux64/komodod/komodod && strip --strip-unneeded  assets/bin/linux64/komodod/komodo-cli
    - yarn install
  script:
    - yarn run dist
    - cd dist
    - chmod 755 ${VERUS_APPIMAGE}
    - tar -czvf ${VERUS_LINUX_TAR} ${VERUS_APPIMAGE}
    - sha256sum ${VERUS_LINUX_TAR} > ${VERUS_LINUX_TAR}.sha256
    - mv ${VERUS_LINUX_TAR} ${VERUS_LINUX_TAR}.sha256 ..
  after_script:
    - curl -F file=@"$VERUS_LINUX_TAR"
      -F channels="$VERUS_POST_CHANNEL"
      -F initial_comment="${POST_COMMENT}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
      - ${VERUS_LINUX_TAR}
      - ${VERUS_LINUX_TAR}.sha256
    expire_in: 1 week

build:linux:arm64:
  image: asherd/agama-builder
  stage: build
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_LINUX="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Linux/Verus-CLI-Linux-v${VERUSCOIN_VERSION}-arm64.tar.gz"
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/Verus-Desktop-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - mkdir -p assets/bin/linux64/verusd
    - gsutil cp $STAGING/$VERUS_CLI_LINUX .
    - tar -xzvf Verus-CLI-Linux-v${VERUSCOIN_VERSION}-arm64.tar.gz --strip=1 --directory assets/bin/linux64/verusd
    - rm Verus-CLI-Linux-v${VERUSCOIN_VERSION}-arm64.tar.gz
    - gsutil cp $STAGING/VerusCoin/Zcash/zcashd-linux-arm64.tar.gz .
    - tar -xzvf zcashd-linux-arm64.tar.gz --directory assets/bin/linux64/
    - rm zcashd-linux-arm64.tar.gz
    - yarn install
  script:
    - yarn run dist --arm64
    - cd dist
    - chmod 755 ${VERUS_APPIMAGE}
    - tar -czvf ${VERUS_LINUX_ARM64_TAR} ${VERUS_APPIMAGE}
    - sha256sum ${VERUS_LINUX_ARM64_TAR} > ${VERUS_LINUX_ARM64_TAR}.sha256
    - mv ${VERUS_LINUX_ARM64_TAR} ${VERUS_LINUX_ARM64_TAR}.sha256 ..
  after_script:
    - curl -F file=@"VERUS_LINUX_ARM64_TAR"
      -F channels="$VERUS_POST_CHANNEL"
      -F initial_comment="${POST_COMMENT}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
      - ${VERUS_LINUX_ARM64_TAR}
      - ${VERUS_LINUX_ARM64_TAR}.sha256
      - dist
    expire_in: 1 week
########################################################################################################################
####END####                                              LINUX                                               ####END####
########################################################################################################################
####START####                                           WINDOWS                                            ####START####
########################################################################################################################
build:windows:
  stage: build
  image: asherd/agama-builder:windows
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_WINDOWS="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Windows/Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip"
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/Verus-Desktop-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - mkdir -p assets/bin/win64/komodod
    - wget https://github.com/KomodoPlatform/komodo/releases/download/${KOMODO_VERSION}/win64_${KOMODO_VERSION}.zip
    - unzip win64_${KOMODO_VERSION}.zip -d assets/bin/komodod
    - rm win64_${KOMODO_VERSION}.zip
    - gsutil cp $STAGING/$VERUS_CLI_WINDOWS .
    - unzip -qq Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip -d assets/bin/win64
    - mv assets/bin/win64/verus-cli assets/bin/win64/verusd
    - strip --strip-unneeded  assets/bin/win64/komodod/komodod.exe && strip --strip-unneeded  assets/bin/win64/komodod/komodo-cli.exe && strip --strip-unneeded  assets/bin/win64/komodod/komodo-tx.exe
    - rm Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip
    - gsutil cp $STAGING/VerusCoin/Zcash/zcashd-win.tar.gz .
    - tar -xzvf zcashd-win.tar.gz -directory assets/bin/win64/
    - rm zcashd-win.tar.gz
    - yarn install
  script:
    - yarn run dist-win
    - cd dist
    - unzip ${VERUS_WINDOWS_ZIP} -d Verus-Desktop-Windows-v${VERUS_VERSION}
    - rm ${VERUS_WINDOWS_ZIP}
    - zip -r ${VERUS_WINDOWS_ZIP} Verus-Desktop-Windows-v${VERUS_VERSION}
    - sha256sum ${VERUS_WINDOWS_ZIP} > ${VERUS_WINDOWS_ZIP}.sha256
    - sha256sum ${VERUS_WINDOWS_NSIS} > ${VERUS_WINDOWS_NSIS}.sha256
    - mv ${VERUS_WINDOWS_NSIS} ${VERUS_WINDOWS_NSIS}.sha256 ..
    - mv ${VERUS_WINDOWS_ZIP} ${VERUS_WINDOWS_ZIP}.sha256  ..
  after_script:
    - curl -F file=@"$VERUS_WINDOWS_ZIP"
      -F channels="$VERUS_POST_CHANNEL"
      -F initial_comment="${POST_COMMENT}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
    - curl -F file=@"$VERUS_WINDOWS_NSIS"
      -F channels="$VERUS_POST_CHANNEL"
      -F initial_comment="${POST_COMMENT}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
      - ${VERUS_WINDOWS_ZIP}
      - ${VERUS_WINDOWS_ZIP}.sha256
      - ${VERUS_WINDOWS_NSIS}
      - ${VERUS_WINDOWS_NSIS}.sha256
    expire_in: 1 week
########################################################################################################################
####END####                                             WINDOWS                                              ####END####
########################################################################################################################
####START####                                            MACOS                                             ####START####
########################################################################################################################
build:mac:
  stage: build
  tags: ["Mojave"]
  before_script:
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_MACOS="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/MacOS/Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz";
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/Verus-Desktop-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - gsutil cp $STAGING/$VERUS_CLI_MACOS .
    - wget https://github.com/KomodoPlatform/komodo/releases/download/${KOMODO_VERSION}/macos_${KOMODO_VERSION}.tar.gz
    - mkdir -p assets/bin/osx/verusd
    - mkdir -p assets/bin/osx/komodod
    - tar -xzf Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz --strip=1 --directory assets/bin/osx/verusd
    - tar -xzvf macos_${KOMODO_VERSION}.tar.gz  --strip=1 --directory assets/bin/osx/komodod
    - rm macos_${KOMODO_VERSION}.tar.gz
    - rm Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz
    - gsutil cp $STAGING/VerusCoin/Zcash/zcashd-macos.tar.gz .
    - tar -xzvf zcashd-macos.tar.gz --directory assets/bin/osx/
    - rm zcashd-macos.tar.gz
    - yarn install
  script:
    - export USE_HARD_LINKS=false
    - yarn run dist
    - cd dist
    - shasum -a 256 ${VERUS_MACOS} > ${VERUS_MACOS}.sha256
    - mv ${VERUS_MACOS} ${VERUS_MACOS}.sha256 ..
  after_script:
    - curl -F file=@"${VERUS_MACOS}"
      -F channels="${VERUS_POST_CHANNEL}"
      -F initial_comment="${POST_COMMENT}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
      - ${VERUS_MACOS}
      - ${VERUS_MACOS}.sha256
    expire_in: 1 week


deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  dependencies:
    - build:linux
    - build:linux:arm64
    - build:windows
    - build:mac
  script:
    - mkdir -p $CI_COMMIT_REF_NAME/Windows
    - mkdir -p $CI_COMMIT_REF_NAME/Linux
    - mkdir -p $CI_COMMIT_REF_NAME/MacOS
    - cp ${VERUS_LINUX_TAR} ${CI_COMMIT_REF_NAME}/Linux
    - cp ${VERUS_LINUX_ARM64_TAR} ${CI_COMMIT_REF_NAME}/Linux
    - cp ${VERUS_WINDOWS_ZIP} ${CI_COMMIT_REF_NAME}/Windows
    - cp ${VERUS_MACOS} ${CI_COMMIT_REF_NAME}/MacOS
    - echo ${AUTH_KEY} > AUTH_KEY.json
    - gcloud auth activate-service-account --key-file AUTH_KEY.json
    - gsutil rsync -r $CI_COMMIT_REF_NAME $STAGING/Verus-Desktop/$CI_COMMIT_REF_NAME/
  artifacts:
    paths:
      - ${VERUS_LINUX_TAR}
      - ${VERUS_LINUX_TAR}.sha256
      - ${VERUS_LINUX_ARM64_TAR}
      - ${VERUS_LINUX_ARM64_TAR}.sha256
      - ${VERUS_WINDOWS_ZIP}
      - ${VERUS_WINDOWS_ZIP}.sha256
      - ${VERUS_WINDOWS_NSIS}
      - ${VERUS_WINDOWS_NSIS}.sha256
      - ${VERUS_MACOS}
      - ${VERUS_MACOS}.sha256
    expire_in: 1 week
