stages:
- build
- test
- deploy
########################################################################################################################
####START####                                     PROJECT LEVEL VARIABLES                                  ####START####
########################################################################################################################
variables:
  DOCKER_DRIVER: overlay2
  DEFAULT_VERUSCOIN_BRANCH: master
  VERUS_CONNECT_VERSION: 0.0.1-alpha
  VERUSCOIN_VERSION: 0.6.0-2
  KOMODO_VERSION: 0.5.0
  BINARY_SOURCE: VerusCoin
  EASYDEX_GUI_BUILD: build.tar.gz
  VERUS_CONNECT_APPIMAGE: VerusConnect-Linux-v${VERUS_CONNECT_VERSION}.AppImage
  VERUS_CONNECT_LINUX_TAR: VerusConnect-Linux-v${VERUS_CONNECT_VERSION}.tar.gz
  VERUS_CONNECT_WINDOWS_ZIP: VerusConnect-Windows-v${VERUS_CONNECT_VERSION}.zip
  VERUS_CONNECT_WINDOWS_NSIS: VerusConnect-Windows-v${VERUS_CONNECT_VERSION}.exe
  VERUS_CONNECT_MACOS: VerusConnect-MacOS-v${VERUS_CONNECT_VERSION}.dmg
  GIT_SUBMODULE_STRATEGY: recursive
  POST_COMMENT: "Pipeline Trigger: ${CI_PIPELINE_SOURCE}\n
      Branch: ${CI_COMMIT_REF_NAME}\n
      Commit: https://github.com/VerusCoin/VerusConnect/commit/${CI_COMMIT_SHA}\n
      ${CI_COMMIT_MESSAGE}\n"
########################################################################################################################
####END####                                        PROJECT LEVEL VARIABLES                                   ####END####
########################################################################################################################
########################################################################################################################
########################################################################################################################
####START####          Build Stage: compile and package komodo binaries for Verus CLI                     ####START#####
########################################################################################################################
########################################################################################################################
####START####                                            LINUX                                             ####START####
########################################################################################################################
build:linux:
  image: asherd/agama-builder
  stage: build
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_LINUX="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Linux/Verus-CLI-Linux-v${VERUSCOIN_VERSION}-amd64.tar.gz"
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/
    - git clone https://github.com/VerusCoin/VerusConnect-GUI.git
    - cd VerusConnect-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - mkdir -p assets/bin/linux64/verusd
    - gsutil cp $STAGING/$VERUS_CLI_LINUX .
    - tar -xzvf Verus-CLI-Linux-v${VERUSCOIN_VERSION}-amd64.tar.gz --strip=1 --directory assets/bin/linux64/verusd
    - rm Verus-CLI-Linux-v${VERUSCOIN_VERSION}-amd64.tar.gz
    - wget https://github.com/KomodoPlatform/komodo/releases/download/0.5.0/komodo_0.5.0_linux.tar.gz
    - tar -xzvf komodo_${KOMODO_VERSION}_linux.tar.gz --strip=1 --directory assets/bin/linux64
    - rm komodo_${KOMODO_VERSION}_linux.tar.gz
    - strip --strip-unneeded  assets/bin/linux64/komodod && strip --strip-unneeded  assets/bin/linux64/komodo-cli
    - yarn install
  script:
    - yarn run dist
    - cd dist
    - chmod 755 ${VERUS_CONNECT_APPIMAGE}
    - tar -czvf ${VERUS_CONNECT_LINUX_TAR} ${VERUS_CONNECT_APPIMAGE}
    - sha256sum ${VERUS_CONNECT_LINUX_TAR} > ${VERUS_CONNECT_LINUX_TAR}.sha256
    - mv ${VERUS_CONNECT_LINUX_TAR} ${VERUS_CONNECT_LINUX_TAR}.sha256 ..
  after_script:
    - curl -F file=@"$VERUS_CONNECT_LINUX_TAR"
      -F channels="$VERUS_CONNECT_POST_CHANNEL"
      -F initial_comment="${POST_COMMENT}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
      - ${VERUS_CONNECT_LINUX_TAR}
      - ${VERUS_CONNECT_LINUX_TAR}.sha256
      - ${VERUS_CONNECT_APPIMAGE}
      - ${VERUS_CONNECT_APPIMAGE}.sha256 ..
      - dist
    expire_in: 1 week
########################################################################################################################
####END####                                              LINUX                                               ####END####
########################################################################################################################
####START####                                           WINDOWS                                            ####START####
########################################################################################################################
build:windows:
  stage: build
  image: asherd/agama-builder:windows
  before_script:
    - echo "$AUTH_KEY" > AUTH_KEY.json &&
      gcloud auth activate-service-account
      --key-file AUTH_KEY.json &&
      rm AUTH_KEY.json
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_WINDOWS="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/Windows/Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip"
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/
    - git clone https://github.com/VerusCoin/VerusConnect-GUI.git
    - cd VerusConnect-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - mkdir -p assets/bin/
    - gsutil cp $STAGING/$VERUS_CLI_WINDOWS .
    - unzip -qq Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip -d assets/bin/win64
    - mv assets/bin/win64/verus-cli assets/bin/win64/verusd
    - wget https://github.com/KomodoPlatform/komodo/releases/download/0.5.0/komodo_0.5.0_windows.zip
    - unzip komodo_${KOMODO_VERSION}_windows.zip -d assets/bin
    - rm komodo_${KOMODO_VERSION}_windows.zip
    - strip --strip-unneeded  assets/bin/win64/komodod.exe && strip --strip-unneeded  assets/bin/win64/komodo-cli.exe && strip --strip-unneeded  assets/bin/win64/komodo-tx.exe
    - rm Verus-CLI-Windows-v${VERUSCOIN_VERSION}.zip
    - yarn install
  script:
    - yarn run dist-win
    - cd dist
    - sha256sum ${VERUS_CONNECT_WINDOWS_ZIP} > ${VERUS_CONNECT_WINDOWS_ZIP}.sha256
    - sha256sum ${VERUS_CONNECT_WINDOWS_NSIS} > ${VERUS_CONNECT_WINDOWS_NSIS}.sha256
    - mv ${VERUS_CONNECT_WINDOWS_ZIP} ${VERUS_CONNECT_WINDOWS_ZIP}.sha256 ${VERUS_CONNECT_WINDOWS_NSIS} ${VERUS_CONNECT_WINDOWS_NSIS}.sha256 ..
  after_script:
    - curl -F file=@"$VERUS_CONNECT_WINDOWS_ZIP"
      -F channels="$VERUS_CONNECT_POST_CHANNEL"
      -F initial_comment="${POST_COMMENT}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
      - ${VERUS_CONNECT_WINDOWS_ZIP}
      - ${VERUS_CONNECT_WINDOWS_ZIP}.sha256
      - ${VERUS_CONNECT_WINDOWS_NSIS}
      - ${VERUS_CONNECT_WINDOWS_NSIS}.sha256
      - dist
    expire_in: 1 week
########################################################################################################################
####END####                                             WINDOWS                                              ####END####
########################################################################################################################
####START####                                            MACOS                                             ####START####
########################################################################################################################
build:mac:
  stage: build
  tags: ["Mojave"]
  before_script:
    - if [ -z "${UPSTREAM_CLI_BRANCH}" ]; then export
      VERUS_CLI_MACOS="${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH}/MacOS/Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz";
      POST_COMMENT="${POST_COMMENT}Using ${BINARY_SOURCE}/${DEFAULT_VERUSCOIN_BRANCH} binaries.";
      else
      export POST_COMMENT="${POST_COMMENT}Using ${UPSTREAM_TRIGGER}/${UPSTREAM_CLI_BRANCH} binaries."; fi
    - cd gui/
    - git clone https://github.com/VerusCoin/VerusConnect-GUI.git
    - cd VerusConnect-GUI/react
    - yarn install
    - yarn run build
    - cd ../../..
    - gsutil cp $STAGING/$VERUS_CLI_MACOS .
    - wget https://github.com/KomodoPlatform/komodo/releases/download/0.5.0/komodo_0.5.0_macOS.gz
    - mkdir -p assets/bin/osx/verusd
    - tar -xzf Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz --strip=1 --directory assets/bin/osx/verusd
    - tar -xzvf komodo_${KOMODO_VERSION}_macOS.gz  --strip=1 --directory assets/bin/osx
    - rm komodo_${KOMODO_VERSION}_macOS.gz
    - rm Verus-CLI-MacOS-v${VERUSCOIN_VERSION}.tar.gz
    - yarn install
  script:
    - export USE_HARD_LINKS=false
    - yarn run dist
    - cd dist
    - shasum -a 256 ${VERUS_CONNECT_MACOS} > ${VERUS_CONNECT_MACOS}.sha256
    - mv ${VERUS_CONNECT_MACOS} ${VERUS_CONNECT_MACOS}.sha256 ..
  after_script:
    - curl -F file=@"${VERUS_CONNECT_MACOS}"
      -F channels="${VERUS_CONNECT_POST_CHANNEL}"
      -F initial_comment="${POST_COMMENT}"
      -H "${SLACK_BOT_AUTH}"
      "https://slack.com/api/files.upload"
  artifacts:
    paths:
      - ${VERUS_CONNECT_MACOS}
      - ${VERUS_CONNECT_MACOS}.sha256
      - dist
    expire_in: 1 week


deploy:
  stage: deploy
  image: google/cloud-sdk:alpine
  dependencies:
    - build:linux
    - build:windows
    - build:mac
  script:
    - mkdir -p $CI_COMMIT_REF_NAME/Windows
    - mkdir -p $CI_COMMIT_REF_NAME/Linux
    - mkdir -p $CI_COMMIT_REF_NAME/MacOS
    - cp ${VERUS_CONNECT_LINUX_TAR} ${CI_COMMIT_REF_NAME}/Linux
    - cp ${VERUS_CONNECT_WINDOWS_ZIP} ${CI_COMMIT_REF_NAME}/Windows
    - cp ${VERUS_CONNECT_MACOS} ${CI_COMMIT_REF_NAME}/MacOS
    - echo ${AUTH_KEY} > AUTH_KEY.json
    - gcloud auth activate-service-account --key-file AUTH_KEY.json
    - gsutil rsync -r $CI_COMMIT_REF_NAME $STAGING/VerusConnect/$CI_COMMIT_REF_NAME/
  artifacts:
    paths:
      - ${VERUS_CONNECT_LINUX_TAR}
      - ${VERUS_CONNECT_LINUX_TAR}.sha256
      - ${VERUS_CONNECT_WINDOWS_ZIP}
      - ${VERUS_CONNECT_WINDOWS_ZIP}.sha256
      - ${VERUS_CONNECT_MACOS}
      - ${VERUS_CONNECT_MACOS}.sha256
  #    - ${VERUS_CONNECT_WINDOWS_NSIS}
   #   - ${VERUS_CONNECT_WINDOWS_NSIS}.sha256
    expire_in: 1 week
